baseURL = 'https://mvalentne.github.io/Blog_TheLearnerBoys/'
locale = 'en-us'
title = 'The Learner Boys'
theme = "hugo-theme-nostyleplease"

# Categorias y etiquetas de post
[taxonomies]
    keyword = "keywords"
    category = "categories"
    author = "authors"

# Lo hago inseguro, es estatico y de colaboracion cerrada.
# Nos permite meter html en medio del markdown, GIFS LOQUISIMOS
[markup.goldmark.renderer]
    unsafe = true

[markup.tableOfContents]
    startLevel = 1
    endLevel = 6

# Apariencia del sistema, (light / dark / auto)
[params]
  [params.theme_config]
    appearance = "light"

# Entrada de menú para la sección de Hilos
[[menu.main]]
  name = "Hilos"
  url = "/hilos/"
  weight = 15

