baseURL = 'https://example.org/'
locale = 'en-us'
title = 'The Learner Boys'
theme = "hugo-theme-nostyleplease"

# Categorias y etiquetas de post
[taxonomies]
    keyword = "keywords"
    category = "categories"
    author = "authors"
